CREATE TABLE IF NOT EXISTS accounts (
    uid INTEGER NOT NULL AUTO_INCREMENT,
    login VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    twitter VARCHAR(255) NOT NULL DEFAULT '',
    twitch VARCHAR(255) NOT NULL DEFAULT '',
    youtube VARCHAR(255) NOT NULL DEFAULT '',
    register DATETIME NOT NULL DEFAULT NOW(),
    activated BOOLEAN NOT NULL DEFAULT TRUE,
    creatorPoints INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY(uid)
);

CREATE TABLE IF NOT EXISTS settings (
    uid INTEGER NOT NULL AUTO_INCREMENT,
    account INTEGER NOT NULL UNIQUE,
    messages INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    friend INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY(uid),
    FOREIGN KEY(account) REFERENCES accounts (uid)
                                    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS players (
    uid INTEGER NOT NULL AUTO_INCREMENT,
    accountId INTEGER NOT NULL UNIQUE,
    stars INTEGER NOT NULL DEFAULT 0,
    demons INTEGER NOT NULL DEFAULT 0,
    coins INTEGER NOT NULL DEFAULT 0,
    userCoins INTEGER NOT NULL DEFAULT 0,
    diamonds INTEGER NOT NULL DEFAULT 0,
    orbs INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY(uid),
    FOREIGN KEY(accountId) REFERENCES accounts (uid)
                                   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skins (
    uid INTEGER NOT NULL AUTO_INCREMENT,
    player INTEGER NOT NULL UNIQUE,
    icon INTEGER NOT NULL DEFAULT 0,
    firstColor INTEGER NOT NULL DEFAULT 0,
    secondColor INTEGER NOT NULL DEFAULT 3,
    iconType INTEGER NOT NULL DEFAULT 0,
    special INTEGER NOT NULL DEFAULT 0,
    accIcon INTEGER NOT NULL DEFAULT 0,
    accShip INTEGER NOT NULL DEFAULT 0,
    accBall INTEGER NOT NULL DEFAULT 0,
    accBird INTEGER NOT NULL DEFAULT 0,
    accDart INTEGER NOT NULL DEFAULT 0,
    accRobot INTEGER NOT NULL DEFAULT 0,
    accGlow INTEGER NOT NULL DEFAULT 0,
    accSpider INTEGER NOT NULL DEFAULT 0,
    accExplosion INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY(uid),
    FOREIGN KEY(player) REFERENCES players (uid)
                                 ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile_comments (
    uid INTEGER NOT NULL AUTO_INCREMENT,
    owner INTEGER NOT NULL,
    text TEXT NOT NULL,
    time DATETIME NOT NULL DEFAULT NOW(),
    spam BOOLEAN NOT NULL DEFAULT FALSE,
    likes INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY(uid),
    FOREIGN KEY(owner) REFERENCES accounts (uid)
                                            ON DELETE CASCADE
);